name: my-keras
channels:
- rdkit
- defaults
dependencies:
- _libgcc_mutex=0.1=main
- alabaster=0.7.10=py35h6fb19ab_0
- anaconda=5.2.0=py35_3
- anaconda-client=1.6.14=py35_0
- anaconda-project=0.8.2=py35h7d62c80_0
- asn1crypto=0.24.0=py35_0
- astroid=1.6.3=py35_0
- astropy=3.0.2=py35h3010b51_1
- attrs=18.1.0=py35_0
- babel=2.5.3=py35_0
- backcall=0.1.0=py35_0
- backports=1.0=py35hd471ac7_1
- backports.shutil_get_terminal_size=1.0.0=py35h40844db_2
- beautifulsoup4=4.6.0=py35h442a8c9_1
- biopython=1.72=py35h04863e7_0
- bitarray=0.8.1=py35h14c3975_1
- bkcharts=0.2=py35he4f7e30_0
- blas=1.0=mkl
- blaze=0.11.3=py35ha2c9137_0
- bleach=2.1.3=py35_0
- blosc=1.14.3=hdbcaa40_0
- bokeh=0.12.16=py35_0
- boto=2.48.0=py35h2cfd601_1
- bottleneck=1.2.1=py35he1b16f1_0
- bzip2=1.0.6=h14c3975_5
- ca-certificates=2018.03.07=0
- cairo=1.14.12=h7636065_2
- certifi=2018.4.16=py35_0
- cffi=1.11.5=py35h9745a5d_0
- chardet=3.0.4=py35hb6e9ddf_1
- click=6.7=py35h353a69f_0
- cloudpickle=0.5.3=py35_0
- clyent=1.2.2=py35h491ffcb_1
- colorama=0.3.9=py35h81e2b6c_0
- contextlib2=0.5.5=py35h6690dba_0
- cryptography=2.2.2=py35h14c3975_0
- curl=7.60.0=h84994c4_0
- cycler=0.10.0=py35hc4d5149_0
- cython=0.28.2=py35h14c3975_0
- cytoolz=0.9.0.1=py35h14c3975_0
- dask=0.17.5=py35_0
- dask-core=0.17.5=py35_0
- datashape=0.5.4=py35h5b068ae_0
- dbus=1.13.2=h714fa37_1
- decorator=4.3.0=py35_0
- distributed=1.21.8=py35_0
- docutils=0.14=py35hd11081d_0
- entrypoints=0.2.3=py35h48174a2_2
- et_xmlfile=1.0.1=py35hde8d43e_0
- expat=2.2.5=he0dffb1_0
- fastcache=1.0.2=py35h14c3975_2
- filelock=3.0.4=py35_0
- flask=1.0.2=py35_1
- flask-cors=3.0.4=py35_0
- fontconfig=2.12.6=h49f89f6_0
- freetype=2.8=hab7d2ae_1
- get_terminal_size=1.0.0=haa9412d_0
- gevent=1.3.0=py35h14c3975_0
- glib=2.56.1=h000015b_0
- glob2=0.6=py35hff66265_0
- gmp=6.1.2=h6c8ec71_1
- gmpy2=2.0.8=py35hd0a1c9a_2
- graphite2=1.3.11=h16798f4_2
- greenlet=0.4.13=py35h14c3975_0
- gst-plugins-base=1.14.0=hbbd80ab_1
- gstreamer=1.14.0=hb453b48_1
- h5py=2.7.1=py35ha1f6525_2
- harfbuzz=1.7.6=h5f0a787_1
- hdf5=1.10.2=hba1933b_1
- heapdict=1.0.0=py35_2
- html5lib=1.0.1=py35h2f9c1c0_0
- icu=58.2=h9c2bf20_1
- idna=2.6=py35h8605a33_1
- imageio=2.3.0=py35_0
- imagesize=1.0.0=py35_0
- intel-openmp=2018.0.0=8
- ipykernel=4.8.2=py35_0
- ipython=6.4.0=py35_0
- ipython_genutils=0.2.0=py35hc9e07d0_0
- ipywidgets=7.2.1=py35_0
- isort=4.3.4=py35_0
- itsdangerous=0.24=py35h7c46880_1
- jbig=2.1=hdba287a_0
- jdcal=1.4=py35_0
- jedi=0.12.0=py35_1
- jinja2=2.10=py35h480ab6d_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py35h4395190_0
- jupyter=1.0.0=py35_4
- jupyter_client=5.2.3=py35_0
- jupyter_console=5.2.0=py35h4044a63_1
- jupyter_core=4.4.0=py35ha89e94b_0
- jupyterlab=0.32.1=py35_0
- jupyterlab_launcher=0.10.5=py35_0
- kiwisolver=1.0.1=py35hcb1117a_0
- lazy-object-proxy=1.3.1=py35h4c720c6_0
- libboost=1.65.1=habcd387_4
- libcurl=7.60.0=h1ad7b7a_0
- libedit=3.1.20170329=h6b74fdf_2
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=hdf63c60_3
- libgfortran-ng=7.2.0=hdf63c60_3
- libpng=1.6.34=hb9fc6fc_0
- libsodium=1.0.16=h1bed415_0
- libssh2=1.8.0=h9cfc8f7_4
- libstdcxx-ng=7.2.0=hdf63c60_3
- libtiff=4.0.9=he85c1e1_1
- libtool=2.4.6=h544aabb_3
- libxcb=1.13=h1bed415_1
- libxml2=2.9.8=h26e45fe_1
- libxslt=1.1.32=h1312cb7_0
- llvmlite=0.23.1=py35hdbcaa40_0
- locket=0.2.0=py35h170bc82_1
- lxml=4.2.1=py35h23eabaa_0
- lzo=2.10=h49e0be7_2
- markupsafe=1.0=py35h4f4fcf6_1
- matplotlib=2.2.2=py35h0e671d2_1
- mccabe=0.6.1=py35hd8c1f23_1
- mistune=0.8.3=py35h14c3975_1
- mkl=2018.0.2=1
- mkl-service=1.1.2=py35h0fc7090_4
- mkl_fft=1.0.1=py35h3010b51_0
- mkl_random=1.0.1=py35h629b387_0
- more-itertools=4.1.0=py35_0
- mpc=1.0.3=hec55b23_5
- mpfr=3.1.5=h11a74b3_2
- mpmath=1.0.0=py35h7ce6e34_2
- msgpack-python=0.5.6=py35h6bb024c_0
- multipledispatch=0.5.0=py35_0
- nbconvert=5.3.1=py35hc5194e3_0
- nbformat=4.4.0=py35h12e6e07_0
- ncurses=6.1=hf484d3e_0
- networkx=2.1=py35_0
- nltk=3.3.0=py35_0
- nose=1.3.7=py35hdc64897_2
- notebook=5.5.0=py35_0
- numba=0.38.0=py35h637b7d7_0
- numexpr=2.6.5=py35h7bf3b9c_0
- numpy=1.14.3=py35hcd700cb_1
- numpy-base=1.14.3=py35h9be14a7_1
- numpydoc=0.8.0=py35_0
- odo=0.5.1=py35h102315f_0
- olefile=0.45.1=py35_0
- openpyxl=2.5.3=py35_0
- openssl=1.0.2o=h20670df_0
- packaging=17.1=py35_0
- pandas=0.23.0=py35h637b7d7_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py35h1565a15_1
- pango=1.41.0=hd475d92_0
- parso=0.2.0=py35_0
- partd=0.3.8=py35h68187f2_0
- patchelf=0.9=hf79760b_2
- path.py=11.0.1=py35_0
- pathlib2=2.3.2=py35_0
- patsy=0.5.0=py35_0
- pcre=8.42=h439df22_0
- pep8=1.7.1=py35_0
- pexpect=4.5.0=py35_0
- pickleshare=0.7.4=py35hd57304d_0
- pillow=5.1.0=py35h3deb7b8_0
- pip=10.0.1=py35_0
- pixman=0.34.0=hceecf20_3
- pkginfo=1.4.2=py35_1
- pluggy=0.6.0=py35hb428803_0
- ply=3.11=py35_0
- prompt_toolkit=1.0.15=py35hc09de7a_0
- psutil=5.4.5=py35h14c3975_0
- ptyprocess=0.5.2=py35h38ce0a3_0
- py=1.5.3=py35_0
- py-boost=1.65.1=py35hf484d3e_4
- pycodestyle=2.4.0=py35_0
- pycosat=0.6.3=py35h6b6bb97_0
- pycparser=2.18=py35h61b3040_1
- pycrypto=2.6.1=py35h14c3975_8
- pycurl=7.43.0.1=py35hb7f436b_0
- pyflakes=1.6.0=py35hd1da72e_0
- pygments=2.2.0=py35h0f41973_0
- pylint=1.8.4=py35_0
- pyodbc=4.0.23=py35hf484d3e_0
- pyopenssl=18.0.0=py35_0
- pyparsing=2.2.0=py35h041ed72_1
- pyqt=5.9.2=py35h751905a_0
- pysocks=1.6.8=py35_0
- pytables=3.4.3=py35h02b9ad4_2
- pytest=3.5.1=py35_0
- pytest-arraydiff=0.2=py35_0
- pytest-astropy=0.3.0=py35_0
- pytest-doctestplus=0.1.3=py35_0
- pytest-openfiles=0.3.0=py35_0
- pytest-remotedata=0.2.1=py35_0
- python=3.5.5=hc3d631a_4
- python-dateutil=2.7.3=py35_0
- pytz=2018.4=py35_0
- pywavelets=0.5.2=py35h53ec731_0
- pyyaml=3.12=py35h46ef4ae_1
- pyzmq=17.0.0=py35h14c3975_0
- qt=5.9.5=h7e424d6_0
- qtawesome=0.4.4=py35hd68ff89_0
- qtconsole=4.3.1=py35h4626a06_0
- qtpy=1.4.1=py35_0
- readline=7.0=ha6073c6_4
- requests=2.18.4=py35hb9e6ad1_1
- rope=0.10.7=py35h986144c_0
- ruamel_yaml=0.15.35=py35h14c3975_1
- scikit-image=0.13.1=py35h14c3975_1
- scikit-learn=0.19.1=py35hbf1f462_0
- scipy=1.1.0=py35hfc37229_0
- seaborn=0.8.1=py35h04cba02_0
- send2trash=1.5.0=py35_0
- setuptools=39.1.0=py35_0
- simplegeneric=0.8.1=py35_2
- singledispatch=3.4.0.3=py35h0cd4ec3_0
- sip=4.19.8=py35hf484d3e_0
- six=1.11.0=py35h423b573_1
- snappy=1.1.7=hbae5bb6_3
- snowballstemmer=1.2.1=py35h5435977_0
- sortedcollections=0.6.1=py35_0
- sortedcontainers=1.5.10=py35_0
- sphinx=1.7.4=py35_0
- sphinxcontrib=1.0=py35hcb7efd2_1
- sphinxcontrib-websupport=1.0.1=py35h3537809_1
- spyder=3.2.8=py35_0
- sqlalchemy=1.2.7=py35h6b74fdf_0
- sqlite=3.23.1=he433501_0
- statsmodels=0.9.0=py35h3010b51_0
- sympy=1.1.1=py35h919b29a_0
- tblib=1.3.2=py35hf1eb0b4_0
- terminado=0.8.1=py35_1
- testpath=0.3.1=py35had42eaf_0
- tk=8.6.7=hc745277_3
- toolz=0.9.0=py35_0
- tornado=5.0.2=py35_0
- traitlets=4.3.2=py35ha522a97_0
- typing=3.6.4=py35_0
- unicodecsv=0.14.1=py35h4805c0c_0
- unixodbc=2.3.6=h1bed415_0
- urllib3=1.22=py35h2ab6e29_0
- wcwidth=0.1.7=py35hcd08066_0
- webencodings=0.5.1=py35hb6cf162_1
- werkzeug=0.14.1=py35_0
- wheel=0.31.1=py35_0
- widgetsnbextension=3.2.1=py35_0
- wrapt=1.10.11=py35hfdafd39_0
- xlrd=1.1.0=py35h45a0a2a_1
- xlsxwriter=1.0.4=py35_0
- xlwt=1.3.0=py35h884a0cf_0
- xz=5.2.4=h14c3975_4
- yaml=0.1.7=had09818_2
- zeromq=4.2.5=h439df22_0
- zict=0.1.3=py35h29275ca_0
- zlib=1.2.11=ha838bed_2
- rdkit=2018.03.4.0=py35h71b666b_1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.10.5
  - keras==2.0.5
  - markdown==3.1
  - mkl-fft==1.0.0
  - mkl-random==1.0.1
  - prompt-toolkit==1.0.15
  - protobuf==3.7.1
  - ruamel-yaml==0.15.35
  - tables==3.4.3
  - tensorflow-gpu==1.3.0
  - tensorflow-tensorboard==0.1.8
  - tflearn==0.3.2
  - theano==1.0.4
prefix: /scratch/user/wudi930320/.conda/envs/my-keras

